// C snippets
{"if", "if () {\n\n}", 4, 8},
{"elif", "else if () {\n\n}", 9, 13},

{"void", "void () {\n\n}", 5, 10},
{"fori",     "for (i32 i = 0; i < ; i++) {\n\n}", 20, 14},
{"forx",     "for (i32 x = 0; x < ; x++) {\n\n}", 20, 14},
{"fory",     "for (i32 y = 0; y < ; y++) {\n\n}", 20, 14},
{"forw",     "for (i32 x = 0; x < GRID_WIDTH; x++) {\n\n}", 39, 30},
{"forh",     "for (i32 y = 0; y < GRID_HEIGHT; y++) {\n\n}", 40, 31},
{"switch", "switch () {\ncase : {\n\n} break;\ndefault: {\n\n} break;\n}", 7, 11},
{"case", "case : {\n\n} break;", 5, 9},

{"struct", "typedef struct {\n\n} ;", 20, 17},
{"enum", "typedef enum {\n\n} ;", 18, 15},
