// C snippets
//{"if", "if  {\n\n}", 3, 7},
//{"elif", "else if  {\n\n}", 7, 11},

//{"void", "void () {\n\n}", 5, 10},
{"fori",     "for i in 0..< {\n\n}", 13, 16},
{"forx",     "for x in 0..< {\n\n}", 13, 16},
{"fory",     "for y in 0..< {\n\n}", 13, 16},
{"forw",     "for w in 0..< {\n\n}", 13, 16},
{"forh",     "for h in 0..< {\n\n}", 13, 16},
//{"forx",     "for (i32 x = 0; x < ; x++) {\n\n}", 20, 14},
//{"fory",     "for (i32 y = 0; y < ; y++) {\n\n}", 20, 14},
//{"forw",     "for (i32 x = 0; x < GRID_WIDTH; x++) {\n\n}", 39, 30},
//{"forh",     "for (i32 y = 0; y < GRID_HEIGHT; y++) {\n\n}", 40, 31},
//{"switch", "switch () {\ncase : break;\ndefault: break;\n}", 8, 17},
//{"case", "case : {\n\n} break;", 5, 9},
//{"result", "result = ;\nreturn result;", 9, 0},

//{"struct", "struct {\n\n} ;", 20, 17},
//{"enum", "typedef enum {\n\n} ;", 18, 15},

{"print", "fmt.println(\"\");", 13, 0},